# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentialsmodel',
            old_name='id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='flowmodel',
            old_name='id',
            new_name='session',
        ),
    ]
