# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0002_auto_20160411_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='credentialsmodel',
            name='session',
        ),
        migrations.AddField(
            model_name='credentialsmodel',
            name='doctor',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='oauth2.Doctor'),
            preserve_default=False,
        ),
    ]
